### ISSUE TITLE
폴더 이름 추가 관련

### ISSUE THREAD

**Issue by yebonkim** [AUSG/ausg-seminar-2019#10]
2개의 터미널 창을 여시고, 1개의 창에는 react 프로젝트가 있는 곳으로 이동해주시고 나머지 1개의 창에서는 express 프로젝트가 있는 곳으로 이동해주세요.

위의 부분을 react -> image-to-text폴더, express -> server폴더라고 언급해주시면 더 잘 따라오실 수 있지 않을까 싶습니다!

**Comment by ravieeeee** [comment]
푸시했습니다! e7eb2d5a7eb99c51a36d2a41475000830117535b
