### ISSUE TITLE
삭제 튜토리얼 관련

### ISSUE THREAD

**Issue by yebonkim** [AUSG/ausg-seminar-2019#11]
과금이 일어나지 않도록 삭제 가이드를 추가해주세요...!

**Comment by ravieeeee** [comment]
rekognition은 어떤 인스턴스를 띄우거나 하지 않고 요청 처리별로 과금되기 때문에 따로 삭제할 리소스는 없는 걸로 알고있습니다,,! (https://aws.amazon.com/ko/rekognition/pricing/)

**Comment by yebonkim** [comment]
오홋 그렇군요. 새로 알아갑니다 ㅎㅎ
