### ISSUE TITLE
npm install axios

### ISSUE THREAD

**Issue by yebonkim** [AUSG/ausg-seminar-2019#12]
통신하기 md 파일과 express md 파일에 중복으로 설치합니다!

**Comment by yebonkim** [comment]
헉 혹시 두 번다 설치하는게 맞는것일까요?

**Comment by ravieeeee** [comment]
네! express.md 내에서는 서버에 axios 패키지를 추가하는 것이고, 통신하기.md 내에서는 클라이언트(리액트 프로젝트)단에 axios 패키지를 추가하는 겁니당!
음.. 관련 설명을 추가해야 할까요?

**Comment by yebonkim** [comment]
으으음 이건 제가 웹을 몰라서 모르는 사항같은데 세미나 시에 이 부분을 설명해주시면 좋을 것 같아용!

**Comment by ravieeeee** [comment]
옙! 알겠습니당
