### ISSUE TITLE
디렉토리 정리

### ISSUE THREAD

**Issue by rayleighko** [AUSG/ausg-seminar-2019#13]
혹시 작업하시면서 디렉터리를 정리해주실 수 있으신가요?! 제가 지금 수정하면 혹시 pull을 받아야 하는 등 작업에 지장이 생기실 수 있을 것 같아서요! 만약 시간이 되신다면 번거롭지만 WebTrack2와 WevTrack3 디렉터리의 이름을 2와 3으로 바꾸어 WebTrack으로 이동시켜 주세요!

최종 디렉터리 주소는 다음과 같습니다!
- WebTrack/preparation
- WebTrack/2
- WebTrack/3
- WebTrack/4

**Comment by rayleighko** [comment]
ausgapp이라는 디렉터리도 지워주시면 감사합니다!

**Comment by ravieeeee** [comment]
아하 넵! ausgapp은 명진님이 올리신거 같은데 제가 함께 지워도 문제 없는 건가욥??

**Comment by rayleighko** [comment]
넵! 초이님 세션 지원 때문에 잠깐 만든 거라서 지워도 문제없습니다!

**Comment by ravieeeee** [comment]
푸시했습니다! 56fbd61ed3189a38276704308eca2b00ae64ffc7
