### ISSUE TITLE
[WEB2] 이미지 엑스박스

### ISSUE THREAD

**Issue by onestone9900** [AUSG/ausg-seminar-2019#15]
안녕하세요. WEB2 Track을 듣었었는데요!

좀 늦었지만 어드밴스드 해볼려고 했는데요
WEB2 Track 이미지가 없어서 진행이 힘듭니다.....ㅠ

죄송하지만 확인해주실수 있을까요?

**Comment by rayleighko** [comment]
해당 부분 수정되었습니다. :)

**Comment by onestone9900** [comment]
> 해당 부분 수정되었습니다. :)

감사합니다~!!!   ! :)
