### ISSUE TITLE
submit 버튼 설명 부분 관련

### ISSUE THREAD

**Issue by yebonkim** [AUSG/ausg-seminar-2019#9]
입력하여 바뀐 Form 내부의 state인 imageURL이 App.js가 props로 전달한 getResult 함수를 통해 App.js의 state인 result가 바뀌고 있네요.

윗 부분 사실 제가 웹 개발을 안해봐서 무슨 말인지 잘 모르겠습니당 ㅎㅎ... 주영님께서 세션 중에 다시 한 번 자세하게 설명해주세용!

**Comment by ravieeeee** [comment]
중간에 ppt 띄우고 react 설명할 때 어떤 구조로 돌아가는지 설명할 예정입니다! 그럼 ppt를 조금 더 자세히 해놓을게용
